---
- name: include os variables
  include_vars: "{{jpegoptim_os}}.yml"
  when: jpegoptim_os is defined and jpegoptim_os != ""

################################################################################################

- name: install jpegoptim
  apt: pkg={{jpegoptim_package}} state=present update_cache=yes cache_valid_time=3600